language: java

#jdk:
#  - oraclejdk8

sudo: false

matrix:
  include:
   # Headless Linux
      - os: linux
        dist: trusty
        jdk: oraclejdk8
        env:
          - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"


addons:
  apt:
    packages:
      - oracle-java8-installer

script:
- mvn clean verify
- mvn cobertura:clean
- mvn cobertura:cobertura